### ISSUE TITLE
要同時使用多個數據庫連線該怎麼用?

### ISSUE THREAD

**Issue by HikaruChiu** [yuzd/AntMgr#11]
我設定了兩條SQL連線，我要如何同時都使用?
"ConnectionItemList": [
        {
          "Name": "PJW_DB",
          "ConnectionString": "Data Source=.;Initial Catalog=xxxxxx;User ID=sa;Password=xxxxxxx;MultipleActiveResultSets=true",
          "DatabaseType": "Master"
        },
        {
          "Name": "IntranetDB",
          "ConnectionString": "Data Source=.;Initial Catalog=xxxxxx;User ID=sa;Password=xxxxxxxxx!;MultipleActiveResultSets=true",
          "DatabaseType": "Master"
        }
      ]

**Comment by yuzd** [comment]
在DbModel下 copy一份  ant.mssql.json 。然后改成你新加的db。
然后用插件生成代码。生成代码后。

在DbModel下的DbContext.cs 类里面参考

![image](https://images4.c-ctrip.com/target/0zb1r120008zf32bv3485.png)

加一个

**Comment by HikaruChiu** [comment]
謝謝指教，我試試看
