### ISSUE TITLE
再次打擾

### ISSUE THREAD

**Issue by HikaruChiu** [yuzd/AntMgr#12]
**再次打擾，根據你的源碼，我想知道auth.js是在哪引入?**
![image](https://user-images.githubusercontent.com/4565699/134465181-2ca76cce-8812-470d-979d-97dc5dce402a.png)
**因為我加了一個button，想知道如何顯現?**
![image](https://user-images.githubusercontent.com/4565699/134465334-bcfc5337-9f4a-4528-a9f6-70e72ae507c0.png)

**Comment by yuzd** [comment]
看下wiki 有一步步的教程 https://github.com/yuzd/AntMgr/wiki

**Comment by HikaruChiu** [comment]
好的，那份文件寫得很好。
非常感謝你的分享，讓我能夠學得更多!

**Comment by yuzd** [comment]
好的有问题在和我说
