### ISSUE TITLE
MS SQL 脚本初始化问题

### ISSUE THREAD

**Issue by shawdren** [yuzd/AntMgr#3]
MS Sql的初始化脚本中还有2个小问题。

1 system_role中少2个字段
RoleName和Description，用CodeGen生成成功后代码会报错。

2 插入默认数据的语句，去掉主键列，ms sql默认自增长列是不要显示添加值的，否则脚本会报错，或者关闭自增长的设置，脚本如下：
`
INSERT INTO dbo.system_menu ( DataChangeLastTime, IsActive, ParentTid, Name, Ico, Url, OrderRule, Level, Class) VALUES ( '2019-05-15 18:59:43.000', 1, 0, '系统管理', null, '#', 3, 1, 'glyphicon glyphicon-cog');
INSERT INTO dbo.system_menu ( DataChangeLastTime, IsActive, ParentTid, Name, Ico, Url, OrderRule, Level, Class) VALUES ( '2019-07-01 13:49:10.000', 1, 1, '菜单管理', null, '~/Home/MenuList', 1, 2, 'fa fa-reorder');
INSERT INTO dbo.system_menu ( DataChangeLastTime, IsActive, ParentTid, Name, Ico, Url, OrderRule, Level, Class) VALUES ( '2019-07-01 13:49:52.000', 1, 1, '权限配置', null, '~/Role/RoleAction', 2, 2, 'fa fa-shield');
INSERT INTO dbo.system_menu ( DataChangeLastTime, IsActive, ParentTid, Name, Ico, Url, OrderRule, Level, Class) VALUES ( '2019-07-01 13:52:58.000', 1, 1, '角色管理', null, '~/Role/RoleList', 3, 2, 'fa fa-th-large');
INSERT INTO dbo.system_menu ( DataChangeLastTime, IsActive, ParentTid, Name, Ico, Url, OrderRule, Level, Class) VALUES ( '2019-07-01 13:53:15.000', 1, 1, '系统用户', null, '~/Account/UserList', 4, 2, 'fa fa-users');
INSERT INTO dbo.system_menu ( DataChangeLastTime, IsActive, ParentTid, Name, Ico, Url, OrderRule, Level, Class) VALUES ( '2019-07-01 13:53:32.000', 1, 1, '代码生成', null, '~/Common/CodeGen', 5, 2, 'fa fa-clone');
INSERT INTO dbo.system_users( DataChangeLastTime, IsActive, Eid, UserName, Pwd, Phone, LoginIp, MenuRights, RoleTid, LastLoginTime, UserAgent, CreateRoleName, CreateUser) VALUES ('2019-05-15 18:59:49.000', 1, 'zdyu', '俞正东', 'e10adc3949ba59abbe56e057f20f883e', '1300000000', '127.0.0.1', null, 0, '2019-07-01 13:47:55.000', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36', null, null);`

**Comment by yuzd** [comment]
哦，第一个问题我估计忘记导出最新的。
第二个问题我我没注意，一会修复下

**Comment by shawdren** [comment]
ant.db.json 中有个配置：  "BaseEntityClass": "LinqToDBEntity", //可选：生成的DTo继父类class名称
这个不是可选的，而且不能修改，后面读表的时候用的是这个关键字。
再请教个问题：如果是多表关联查询的数据，在列表上 是不是只能手动绑定数据了

**Comment by yuzd** [comment]
@shawdren 你说的是对的。 "BaseEntityClass": "LinqToDBEntity"的说明文字我修改了。

多表查询的返回体的话需要在页面上的列表的field名称
依照你的返回模型修改就好了。

**Comment by shawdren** [comment]
好的，谢谢
