### ISSUE TITLE
缺少SystemMenu和SystemUsers引用 

### ISSUE THREAD

**Issue by zangxx66** [yuzd/AntMgr#4]
缺少SystemMenu和SystemUsers引用 ，没编译成功

**Comment by zangxx66** [comment]
mysql也不能导入，提示codeGen success，可是并没有看到表被创建

**Comment by yuzd** [comment]
@zangxx66  我测试用的mysql版本是 5.7 。。你的mysql版本是多少。我怀疑是版本之间有些区别。 你打开看下初始化的sql脚本。一个个的执行 看哪个出问题？

**Comment by zangxx66** [comment]
@yuzd 你每个语句结束都要加上分号，但是，复制到mysql倒是可以执行，用插件虽然提示成功但实际没有建表

**Comment by yuzd** [comment]
插件并不是建表哦，别理解错，插件是用来一键生成dbmodels的

表需要你用我提供的建表的脚本的！！

**Comment by zangxx66** [comment]
这样啊，插件是生成CRUD的吧，我只需要在控制器写业务逻辑就ok了吗

**Comment by yuzd** [comment]
@zangxx66 你看wiki 一步步来！！
