### ISSUE TITLE
DbModel新增model耦合性有点高

### ISSUE THREAD

**Issue by cyneck** [yuzd/AntMgr#6]
DbModels.cs文件中增加一个新表，增加一个实体对象后，就可以用代码生成了。生成以后做个微调，不过比较麻烦的是，但是在请求分页list时，DbContext中新表的provider是null，应该是还要在AntEntity中做修改。json配置方式生成代码看似好用，但是确增加了学习成本，总体而言，还不是那么好用。这个框架有点spring data jpa的味道。总体而言还是挺好的。

**Comment by yuzd** [comment]
Dbmodels生成插件是支持每个model一个cs文件的，都是partial的，你可以自己写代码新增也是可以的，可以和代码生成的不耦合。

**Comment by yuzd** [comment]
加了一个wiki来说明dbmodels插件的使用 可以看下 如果有啥意见欢迎提出，谢谢
 https://github.com/yuzd/AntMgr/wiki/4-Dbmodels%E6%8F%92%E4%BB%B6%E7%9B%B8%E5%85%B3
