### ISSUE TITLE
升级到3.1以后cookie为空

### ISSUE THREAD

**Issue by wfjohnny** [yuzd/AntMgr#8]
新增用户配置好权限，再登录时cookie没有取到

**Comment by yuzd** [comment]
升3.1很早的事了，你debug下看看，我没有再现你这个问题

**Comment by wfjohnny** [comment]
debug过程中登录以后cookie没有写入，浏览器里没有cookie信息，userAgent是Chrome/6

**Comment by wfjohnny** [comment]
除了上帝模式的用户可以登录，新增的任何用户都不能登录，userAgent用过Chrome/69，Chrome/88

**Comment by wfjohnny** [comment]
调用logon接口前端有返回token，这时在浏览器cookie里没有cookie，用上帝模式的用户没有此问题
