### ISSUE TITLE
3.1的版本新建的用户不能登录

### ISSUE THREAD

**Issue by wfjohnny** [yuzd/AntMgr#9]
debug过程中登录以后cookie没有写入，浏览器里没有cookie信息，userAgent是Chrome/6
除了上帝模式的用户可以登录，新增的任何用户都不能登录，userAgent用过Chrome/69，Chrome/88
调用logon接口前端有返回token，这时在浏览器cookie里没有cookie，用上帝模式的用户没有此问题

**Comment by yuzd** [comment]
你是我的项目拉下来直接跑就有这样的问题，还是你改造后出现的？

**Comment by wfjohnny** [comment]
没有改造，在增加功能的时候创建了一个新用户以后测试出来的

**Comment by wfjohnny** [comment]
没有改造，在增加功能的时候创建了一个新用户以后测试出来的，原有的底层这块没改动过

**Comment by yuzd** [comment]
我刚刚对照着我写的wiki
 https://github.com/yuzd/AntMgr/wiki/1.%E5%BC%80%E5%8F%91%E4%B8%80%E4%B8%AA%E5%85%B7%E4%BD%93%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6%E7%9A%84helloworld%E9%A1%B5%E9%9D%A2
测试了一遍 没有问题。

**Comment by yuzd** [comment]
![image](https://images4.c-ctrip.com/target/0zb4k120008f07a40A5A5.gif)

**Comment by wfjohnny** [comment]
我是在用户登录的时候出现的这个问题，不是在我新增的功能里出现的，加上了 [AuthorizeFilter]标签就会一直循环returnUrl这个参数，我目前的状况就是新增了一个用户配置好权限，然后用这个用户登录，点击登录以后就又跳到登录页面。在debug的时候发现新增的这个用户cookie是没有写入到浏览器里的，在拦截器里会拦截掉，然后又跳到登录页面

**Comment by wfjohnny** [comment]
![image](https://user-images.githubusercontent.com/20964124/107122054-9065a980-68d0-11eb-9421-afbb2f1dcd3a.png)
![image](https://user-images.githubusercontent.com/20964124/107122076-a07d8900-68d0-11eb-8961-32c2ff34bc7a.png)
这是我用上帝模式的用户和新增的一个用户调用登录接口返回到前端的时候的截图

**Comment by yuzd** [comment]
那肯定是你没有按照wiki给这个用户配置角色吧？
你根据wiki来的嘛？

**Comment by wfjohnny** [comment]
是按照wiki上的步骤添加的

**Comment by yuzd** [comment]
有空你家我qq 1877682825
